name: greetings

on:
  - pull_request_target
  - issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi ğŸ‘‹ğŸ½ Thank you for opening your first issue with simpleclub/url_strategy â¤

          You can expect triage from us soon ğŸ™‚
          In the meantime, you can try to search for similar issues in our [issue database].

          [issue database]: https://github.com/simpleclub/url_strategy/issues?q=is%3Aissue
        pr-message: |
          Hi ğŸ‘‹ğŸ½ Thank you for opening your first PR with simpleclub/url_strategy â¤
          
          You can expect a review from us soon â˜ºï¸ 
          In the meantime, please check our [contribution guidelines], the PR checklist, and the PR checks.
          
          [contribution guidelines]: https://github.com/simpleclub/url_strategy/blob/main/CONTRIBUTING.md
